Generate more compact content when copying DL logs
Instead of:
  Time: <time>
  Kind: <kind>
  Message: <message>
  Error: <exception>
each log separated by an empty line, generate:
  <time> [<kind>] <message>
  <exception>
without empty line separating logs.